### ISSUE TITLE
Option to not remove label?

### ISSUE THREAD

**Issue by fmigneault** [github/issue-labeler#12]
I really like the ability to automatically apply labels if a specific word is found, but having the same labels removed because the word is missing can be problematic. 

For instance, I label `bug` to any issue that as that word, but the label was manually tagged as a bug without using the word in the body, it just gets removed at some point and we lose track of the bug!

Maybe something like follows could be considered?

```
bug: 
   add: false
   remove: false
   regex: 
     - bug
     - ....
```
