### ISSUE TITLE
issues with `enabled-versioned-regex` input

### ISSUE THREAD

**Issue by pantoninho** [github/issue-labeler#21]
If I provide `enable-versioned-regex` input, I get the following warning:
![image](https://user-images.githubusercontent.com/14220276/111549011-6c20a680-8773-11eb-8a8a-8808ed3fb56c.png)

If I do not provide this input, I get the following error:
![image](https://user-images.githubusercontent.com/14220276/111549047-7b075900-8773-11eb-9baf-b4d89dde4c8c.png)

**Comment by stephanmiehe** [comment]
What version are you using? Could you share the entire config file that you're using?

**Comment by pantoninho** [comment]
I'm using version 2 and this is the config file:

```
name: "Issue Labeler"
on:
  issues:
    types: [opened, edited]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v2.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/issue-labeler.yml
          enable-versioned-regex: 0
```
