### ISSUE TITLE
unable to auto label all issues with a regex maching any string

### ISSUE THREAD

**Issue by evgenyfadeev** [github/issue-labeler#23]
We want to have all new issues in a repo to be labeled, unfortunately I was unable to set this up. Here is what I have:

labeler:
```
critical:
    - '^.*$'
```

Btw, I've tried `'.*'`, `''` as regexes and nothing worked - i.e. the label was to applied.
The label "critical" was created as a custom label. We are using a PM tool and want all issues from this repo have a bright label.
Thanks!

workflow:
```
name: "Issue Labeler"
on:
  issues:
    types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v2.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0
```
