### ISSUE TITLE
Warning: Unexpected input(s) 'not-before'

### ISSUE THREAD

**Issue by dak1n1** [github/issue-labeler#24]
Hi! It looks like `not-before` has stopped working. I'm getting this error:

```
Warning: Unexpected input(s) 'not-before', valid inputs are ['repo-token', 'configuration-path', 'enable-versioned-regex']
```

I'm using version 2.4. Here's my workflow file:

```
name: Issue Opened Triage

on:
  issues:
    types: [opened]
  workflow_dispatch:
  push:
    branches:
      - testlabelworkflow

permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  issues: write
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  issue_triage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Label new issue
      uses: github/issue-labeler@829a8bf1b184f74cc575b5435093a92c7b846983
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler-issue-triage.yml
        enable-versioned-regex: 0
        not-before: 2021-06-01T00:00:00Z
```

Thanks!
