### ISSUE TITLE
Could not get issue number or issue body from context, exiting

### ISSUE THREAD

**Issue by craicoverflow** [github/issue-labeler#27]
I have a very simple workflow to label all issues with "needs-triage".

Workflow:

```
name: "Issue Labeler"
on:
  issues:
    types: [opened, reopened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v2.4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0
```

Configuration file:

```yaml
needs-triage:
    - '(?i).*.*'
```

However I am getting a "Could not get issue number or issue body from context, exiting" message.

See the workflow run here for full logs: https://github.com/redhat-developer/app-services-cli/runs/3243472455?check_suite_focus=true
