### ISSUE TITLE
Support Pull Requests

### ISSUE THREAD

**Issue by superbrothers** [github/issue-labeler#40]
I would like to use issue-labeler for Pull Requests.

Currently it does not work for Pull Requests in the following workflow:

```yaml
name: Issue Labeler
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v2.4.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0
```
