### ISSUE TITLE
Read default GitHub token

### ISSUE THREAD

**Issue by EndBug** [github/issue-labeler#65]
The `repo-token` input doesn't need to be mandatory, you can read the default value like this:

```yml
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    default: ${{ github.token }}
    required: false
```
