### ISSUE TITLE
HttpError: Resource not accessible by integration

### ISSUE THREAD

**Issue by amerikan** [github/issue-labeler#68]
I keep getting `HttpError: Resource not accessible by integration` when it runs. My config is:

```yaml
name: "Issue Labeler"
on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler-issue-regex.yml
          enable-versioned-regex: 0
          sync-labels: 1
          include-title: 1
```
