### ISSUE TITLE
Issue-labeler removes labels when regex does not match

### ISSUE THREAD

**Issue by robcrystalornelas** [github/issue-labeler#73]
👋🏻 I've setup an `issue-labeler` action that looks for regex in an issue title.

Currently, the README says that for this action:

> Should the regular expression not match, the label will be removed.

**But I want this action to be additive.** So if the title of the created issue says:

"Data analysis for x, y ,z"

Apply the `data` label.

**Currently** if someone else creates an issue called:

"This is another issue for another topic" and manually adds the label `other`

The action will **remove** the `other` label. 

Is there a way to make this action work so that if the regex in title matches what I setup in action it applies the label, otherwise if regex doesn't match, the user-added-labels are kept?

--- 
A bit more context:

I tried setting `sync-labels: 1` as suggested in the README and `sync-labels: ''`  as suggested in previous issues in this repo.  In both instances, previously added labels that didn't align with the regex were removed.

When we look at the [defaults](https://github.com/github/issue-labeler/blob/6ae80f5cf189fd96d96a4a4125c60e87cba0578d/action.yml#LL28C1-L31C17) for `sync-labels` we see:

```yml
  sync-labels:
    description: 'Remove the label from the issue if the label regex does not match'
    required: false
    default: "0"
```

If default is `0`, shouldn't setting `sync-labels: 1` turn syncing on? Should I try some other setting for `sync-labels` like `sync-labels: 0` or `sync-labels: false`?

Thanks!

CC: @MgenGlder

**Comment by stephanmiehe** [comment]
👋  @robcrystalornelas, I wasn't able to reproduce this. Using v3.1 here is what I got:

```yaml
    - name: Label new issue
      uses: github/issue-labeler@v3.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler-issue-triage.yml
        enable-versioned-regex: 0
        not-before: "2021-06-01T00:00:00Z"
        include-title: 1
        sync-labels: 0
```

```yaml
test:
    - '/hello/'
```

In the first test I add the managed `test` label to the issue and despite the regex not matching the content it is not removed. This is because we have `sync-labels` set to `0`.

<img width="1285" alt="Screenshot 2023-07-04 at 8 38 47 AM" src="https://github.com/github/issue-labeler/assets/49914758/408e8841-8390-4997-9778-07180a8b4885">

In the second test the user adds a label which is not part of `.github/labeler-issue-triage.yml` and the content of the issue matches the regex that should apply the `test` label. We can see that the user submitted label remains and the managed `test` label is added
<img width="1283" alt="Screenshot 2023-07-04 at 8 39 21 AM" src="https://github.com/github/issue-labeler/assets/49914758/af12d166-a5df-437f-bb3e-575e7075b8d4">


If I were to add `sync-labels: 1` the first screenshot would show removal of the `test` label. This is because it's a managed label where the regex doesn't match. The second screenshot would not change in this scenario.

Hope this helps. Feel free to reach out on Slack if you get stuck. Be sure to test with a current version since old versions remove user submitted labels
