### ISSUE TITLE
Error running workflow: "Input required and not supplied: repo-token"

### ISSUE THREAD

**Issue by coliff** [github/issue-labeler#74]
I'm running this GH Action workflow on a public repo and it is failing with Failure "Error: Input required and not supplied: repo-token". My workflow is:

```yml
name: 'Issue Labeler'
on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.1
        with:
          configuration-path: .github/issue-labeler.yml
          enable-versioned-regex: 0
```

Any suggestions on how to resolve?

**Comment by coliff** [comment]
Update, I fixed this by adding `repo-token: "${{ secrets.GITHUB_TOKEN }}"` to the config as follows:

```yml
name: 'Issue Labeler'
on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.1
        with:
          configuration-path: .github/issue-labeler.yml
          enable-versioned-regex: 0
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
```

Shouldn't this be included in the README example?
