### ISSUE TITLE
Error: AggregateError 

### ISSUE THREAD

**Issue by andrewjswan** [github/issue-labeler#83]
Error:
```
Configuration file (path: .github/labeler.yml) does not exist locally, fetching via the API
Could not add label(s) Engine to issue #262
Error: AggregateError
```

Workflow:
```
name: "Workflow / Pull Request Labeler"

on:
  pull_request:
    types: [opened, edited]
    
jobs:
  labeler:
    name: Add labels to Pull Request

    runs-on: ubuntu-latest

    steps:
    - name: Add labels to Pull Request
      uses: github/issue-labeler@v3.4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0
        include-title: 1
```
