### ISSUE TITLE
Add example of `enable-versioned-regex`

### ISSUE THREAD

**Issue by gregsdennis** [github/issue-labeler#84]
The readme shows usage of `enable-versioned-regex`, but it doesn't explain what this does or why it should be used.

**Comment by aarikpokras** [comment]
According to action.yml,
```yaml
  enable-versioned-regex:
    description: 'Controls if versioned regex templates are being used'
    required: true
```

In other words, it is required. I have it set to zero.
