### ISSUE TITLE
bug: The action works fine, but there is still an error message

### ISSUE THREAD

**Issue by GaleedGutierrez** [github/issue-labeler#88]
I have the following error message, but the action works fine.

`Configuration file (path: .github/issue-label.yml) does not exist locally, fetching via the API`
![image](https://github.com/user-attachments/assets/21c8e0b3-c543-4785-ba73-15f572211956)

My .github/workflows/labeler.yml:

```yml
---
name: "🔖 Issue Labeler"
on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.4
        with:
          configuration-path: .github/issue-label.yml
          not-before: 2020-01-15T02:54:32Z
          enable-versioned-regex: 0
          include-title: 1
          repo-token: ${{ github.token }}
```

My .github/issue-labeler.yml:

```yml
---
critical:
    - '(critical|urgent)'
```
